language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - tip

before_script:
  - go fmt ./...
  - go vet $(go list ./...)

script:
  - sh testAndCodecoverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)